title: Solarized Blog Theme
email: my.email@example.com
description: >-
  A solarized blog theme for jekyll.
baseurl: "/solarized-blog-theme"
url: ""
github_username: sampleuser
theme: solarized-blog-theme